name: Begin The Hunt!
description: Use when beginning a new bounty hunt
body:
  - type: input
    id: link
    attributes:
      label: Link the bounty file
      description: Paste the link to the file for this bounty to help reviewers find the spec quickly
      placeholder: https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md
    validations:
      required: true

  - type: checkboxes
    id: progress
    attributes:
      label: Mark your progress
      description: Select the blue emoji (**required**) to mark your bounty as started
      options:
        - label: 🔵&nbsp; Started working
          required: true
        - label: 🟢&nbsp; Ready for review
        - label: 🟣&nbsp; Review completed

  - type: textarea
    id: details
    attributes:
      label: Provide relevant details
      description: Provide any relevant details for your bounty which reviewers would find helpful or relevant
    validations:
      required: false
